# Generated by Django 4.1.1 on 2023-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneAccountId', models.BigIntegerField()),
                ('number', models.IntegerField()),
                ('callType', models.CharField(max_length=100)),
                ('timestamp', models.BigIntegerField()),
                ('duration', models.IntegerField()),
                ('simDisplayName', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cachedMatchedNumber', models.CharField(max_length=50)),
                ('cachedNumberType', models.IntegerField()),
            ],
        ),
    ]
